name: P||Cmax problem solver
version: "0.12.20210102"
author: "Jakub Kwiatkowski <jakub.j.kwiatkowski@student.put.poznan.pl>\nMaciej Grześ <>"
args:
    - prompt:
        short: p
        long: prompt
        help: Asks for next file when idle.
    - verbose:
        short: v
        multiple: true
        help: "Sets the level of verbosity.\nVerbosity levels:\n
              \t0 - display only text results.\n
              \t1 - display final result graph.\n
              \t2 - display text results after every full iteration. (quite slow)\n
              \t3 - display result graph after every full iteration. (slow)\n
              \t4 - display text results after every iteration. (slow)\n
              \t5 - display result graph after every iteration. (very very slow)"
    - unbuffered:
        short: ub
        long: unbuffered
        help: Sets whether logging should be unbuffered. Unbuffered logging flush results every iteration.
    - files:
        short: f
        long: files
        help: Specifies input files with data to proceed.
        multiple: true
        takes_value: true
        value_name: FILE
        index: 1
    - logfile:
        short: l
        long: log-file
        help: Specifies log output file.
        value_name: FILE
        default_value: ./logs/data.log
    - kill:
        short: k
        long: kill
        takes_value: true
        value_name: TIME
        multiple: false
        default_value: '120'
subcommands:
    - generate:
        about: Generates test cases
        version: "0.12.20210102"
        args:
            - cores:
                short: c
                long: core-count
                help: Specifies number of cores that should be used in generated case.
                required: true
                multiple: false
                takes_value: true
                value_name: CORE COUNT
            - optimal:
                short: v
                long: optimal-value
                help: Specifies optimal value of makespan for case.
                multiple: false
                takes_value: true
                value_name: OPTIMAL VALUE
            - output:
                short: o
                long: output
                help: Specifies name of output file.
                long_help: "Specifies name of output file.\n
                            Generator creates two output files:\n
                            One with test case (and this one is named '[NAME]') and
                            one with optimal schedule for this test case (this one is named
                            '[NAME].schedule'"
                default_value: ./instances/test.case
